services:
  mongodb:
    image: mongo:6.0
    container_name: mongo-container
    ports:
      - '27017:27017' # Map MongoDB default port
    environment:
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./mongo-data:/data/db # Mount the folder 'mongo-data' on your host to MongoDB's data directory
    command: [ "mongod", "--bind_ip", "0.0.0.0" ] # Bind MongoDB to all IP addresses
    restart: unless-stopped

  # For login use 'admin' and 'pass' as cred.
  mongo-express:
    image: mongo-express
    container_name: mongo-express-container
    restart: always
    ports:
      - "8081:8081" # Access Mongo Express at http://localhost:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb
